//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Utilities/Input/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""74a2d63c-d56e-40c1-8fb3-b5d863329bd9"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""ceb9857a-5f9b-4280-9829-6449daf0daca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""3952ba76-ed8a-467f-9bff-86fc569f298b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitPuzzle"",
                    ""type"": ""Button"",
                    ""id"": ""2a54affd-5f79-4bb0-b3bf-58e6880ec4b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""2b897f4b-fc28-43c5-a522-c69442704706"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Anykey"",
                    ""type"": ""Button"",
                    ""id"": ""44ebee72-387e-4aef-84b5-5732261434e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""c480e120-4e87-4ad7-8512-1f825dd22bae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ContrastMode"",
                    ""type"": ""Button"",
                    ""id"": ""19fab7fd-e07d-45de-9389-2916cd53a3b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""REBINDTEST"",
                    ""type"": ""Button"",
                    ""id"": ""58d63be6-4da3-4705-9816-9aac15f9385b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Logbook"",
                    ""type"": ""Button"",
                    ""id"": ""b43f0dbb-446f-498d-8e0d-09b360af7dca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Axis"",
                    ""id"": ""0bf53775-7fbe-4d75-929b-e14a8457f91b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": ""NormalizeVector2"",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""849924d9-3b2e-473d-a60d-043ddfe14419"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8466c131-468d-478a-99ab-b6dd2966b57e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8c9540d2-1729-4ac3-a9ca-ec27cae85a1f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""256fff70-0bd2-40e4-b5f7-96510458a96c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""39ed72fd-1f47-4b07-9178-73b1dd2d1e78"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xboxcontroller"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""125b7564-f804-44d0-aeb7-1768ea5c58d0"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1362b017-5dac-4a05-b539-af7917f1d25b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=13,y=13)"",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82394bc3-48f9-448b-af9c-7c5875ff1aaa"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""Anykey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90d4db88-97ae-4326-a18b-429a8c16159f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9998e525-3673-4b7c-9ad3-76eae2a20e71"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xboxcontroller"",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45eb080b-dbfe-4265-9a68-72645599fb2e"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""ExitPuzzle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb07d486-b9d5-4fe1-81af-abc8e0bcc3ad"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""xboxcontroller"",
                    ""action"": ""ExitPuzzle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""750247f7-5076-44b9-ab2b-3fd65e39e2d0"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""351b4e3e-9ae8-438a-9352-efc8be4c601b"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""xboxcontroller"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6141eb4b-b7ae-4c77-bd9e-e6a046f7387d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""ContrastMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc975b64-ffba-45e5-81c6-eaacdc1651c9"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""REBINDTEST"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09842e0b-97d1-415a-96d0-0e8fe71908b8"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Logbook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PuzzleDEBUGGER"",
            ""id"": ""2941194f-298e-48b1-aaf1-fb18798b700f"",
            ""actions"": [
                {
                    ""name"": ""calculate solution"",
                    ""type"": ""Button"",
                    ""id"": ""33f15d10-f9d5-48f4-a23d-a8db1dd4a753"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShowSolution"",
                    ""type"": ""Button"",
                    ""id"": ""476d96cc-4f16-4a60-ad17-b3c6a7baaee2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PressAnyButton"",
                    ""type"": ""Button"",
                    ""id"": ""4cee70df-5b01-4643-b4a7-07b5940c8d1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BlindMode"",
                    ""type"": ""Button"",
                    ""id"": ""0138de2d-e3ea-4925-93cf-c16dd65d3f07"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AutoPilotPuzzle"",
                    ""type"": ""Button"",
                    ""id"": ""648b08b0-9ce0-4edf-af91-51b979ec98d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleFullAutopilot"",
                    ""type"": ""Button"",
                    ""id"": ""b43aed17-b847-4357-877b-702de380e37c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SolvePuzzle"",
                    ""type"": ""Button"",
                    ""id"": ""cba23c7b-edf4-48dd-a3a9-9fb7a118578b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5f86de9b-62f1-4b3a-bff5-42d8dd09a060"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""calculate solution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d27998a-7002-42fa-b7ef-974c6a33875e"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShowSolution"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""155990f9-3485-4830-8b4c-04a80baf5ed8"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PressAnyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6322b77d-980c-47e7-b9e8-609edab09bd1"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BlindMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""182fe015-1281-4589-8258-eaae32a5c0dd"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""AutoPilotPuzzle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30075741-e858-4240-945d-1ab19523366a"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""ToggleFullAutopilot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01547e72-e7ae-493f-bdfd-57a1438751b9"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Stnd KBM"",
                    ""action"": ""SolvePuzzle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""96df4aaa-4b8b-4edb-843e-d362b8f1da9f"",
            ""actions"": [
                {
                    ""name"": ""BackToMain"",
                    ""type"": ""Button"",
                    ""id"": ""5f8c38ae-35dd-43b1-89c0-ca5b8464fe39"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RestartScene"",
                    ""type"": ""Button"",
                    ""id"": ""ebe1deb2-5145-4161-8cf2-597a196a11c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1cc9bc13-ef3d-4191-8a52-669d97249e5d"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToMain"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c988f0bb-2ac0-4809-8cf9-b515e48b9b97"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RestartScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OneSwitch"",
            ""id"": ""1c650195-fd7e-4a81-a847-7cc027d7e2a8"",
            ""actions"": [
                {
                    ""name"": ""OnlyButton"",
                    ""type"": ""Button"",
                    ""id"": ""a7c3378b-2aaa-4b9b-8be4-9c3824308de7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PuzzleTest"",
                    ""type"": ""Button"",
                    ""id"": ""244df09a-6c4b-4af8-b9af-307360c847e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5c38d5e4-8db4-4e94-9b86-77535c5e76ed"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnlyButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8cabd77-3209-4838-b88c-e3db55095b28"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PuzzleTest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Stnd KBM"",
            ""bindingGroup"": ""Stnd KBM"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""xboxcontroller"",
            ""bindingGroup"": ""xboxcontroller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XboxOneGampadiOS>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        m_Player_ExitPuzzle = m_Player.FindAction("ExitPuzzle", throwIfNotFound: true);
        m_Player_MoveCamera = m_Player.FindAction("MoveCamera", throwIfNotFound: true);
        m_Player_Anykey = m_Player.FindAction("Anykey", throwIfNotFound: true);
        m_Player_Menu = m_Player.FindAction("Menu", throwIfNotFound: true);
        m_Player_ContrastMode = m_Player.FindAction("ContrastMode", throwIfNotFound: true);
        m_Player_REBINDTEST = m_Player.FindAction("REBINDTEST", throwIfNotFound: true);
        m_Player_Logbook = m_Player.FindAction("Logbook", throwIfNotFound: true);
        // PuzzleDEBUGGER
        m_PuzzleDEBUGGER = asset.FindActionMap("PuzzleDEBUGGER", throwIfNotFound: true);
        m_PuzzleDEBUGGER_calculatesolution = m_PuzzleDEBUGGER.FindAction("calculate solution", throwIfNotFound: true);
        m_PuzzleDEBUGGER_ShowSolution = m_PuzzleDEBUGGER.FindAction("ShowSolution", throwIfNotFound: true);
        m_PuzzleDEBUGGER_PressAnyButton = m_PuzzleDEBUGGER.FindAction("PressAnyButton", throwIfNotFound: true);
        m_PuzzleDEBUGGER_BlindMode = m_PuzzleDEBUGGER.FindAction("BlindMode", throwIfNotFound: true);
        m_PuzzleDEBUGGER_AutoPilotPuzzle = m_PuzzleDEBUGGER.FindAction("AutoPilotPuzzle", throwIfNotFound: true);
        m_PuzzleDEBUGGER_ToggleFullAutopilot = m_PuzzleDEBUGGER.FindAction("ToggleFullAutopilot", throwIfNotFound: true);
        m_PuzzleDEBUGGER_SolvePuzzle = m_PuzzleDEBUGGER.FindAction("SolvePuzzle", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_BackToMain = m_UI.FindAction("BackToMain", throwIfNotFound: true);
        m_UI_RestartScene = m_UI.FindAction("RestartScene", throwIfNotFound: true);
        // OneSwitch
        m_OneSwitch = asset.FindActionMap("OneSwitch", throwIfNotFound: true);
        m_OneSwitch_OnlyButton = m_OneSwitch.FindAction("OnlyButton", throwIfNotFound: true);
        m_OneSwitch_PuzzleTest = m_OneSwitch.FindAction("PuzzleTest", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Sprint;
    private readonly InputAction m_Player_ExitPuzzle;
    private readonly InputAction m_Player_MoveCamera;
    private readonly InputAction m_Player_Anykey;
    private readonly InputAction m_Player_Menu;
    private readonly InputAction m_Player_ContrastMode;
    private readonly InputAction m_Player_REBINDTEST;
    private readonly InputAction m_Player_Logbook;
    public struct PlayerActions
    {
        private @InputMaster m_Wrapper;
        public PlayerActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputAction @ExitPuzzle => m_Wrapper.m_Player_ExitPuzzle;
        public InputAction @MoveCamera => m_Wrapper.m_Player_MoveCamera;
        public InputAction @Anykey => m_Wrapper.m_Player_Anykey;
        public InputAction @Menu => m_Wrapper.m_Player_Menu;
        public InputAction @ContrastMode => m_Wrapper.m_Player_ContrastMode;
        public InputAction @REBINDTEST => m_Wrapper.m_Player_REBINDTEST;
        public InputAction @Logbook => m_Wrapper.m_Player_Logbook;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Sprint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @ExitPuzzle.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExitPuzzle;
                @ExitPuzzle.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExitPuzzle;
                @ExitPuzzle.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExitPuzzle;
                @MoveCamera.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveCamera;
                @Anykey.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnykey;
                @Anykey.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnykey;
                @Anykey.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnykey;
                @Menu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                @Menu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                @Menu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMenu;
                @ContrastMode.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnContrastMode;
                @ContrastMode.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnContrastMode;
                @ContrastMode.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnContrastMode;
                @REBINDTEST.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnREBINDTEST;
                @REBINDTEST.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnREBINDTEST;
                @REBINDTEST.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnREBINDTEST;
                @Logbook.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLogbook;
                @Logbook.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLogbook;
                @Logbook.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLogbook;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @ExitPuzzle.started += instance.OnExitPuzzle;
                @ExitPuzzle.performed += instance.OnExitPuzzle;
                @ExitPuzzle.canceled += instance.OnExitPuzzle;
                @MoveCamera.started += instance.OnMoveCamera;
                @MoveCamera.performed += instance.OnMoveCamera;
                @MoveCamera.canceled += instance.OnMoveCamera;
                @Anykey.started += instance.OnAnykey;
                @Anykey.performed += instance.OnAnykey;
                @Anykey.canceled += instance.OnAnykey;
                @Menu.started += instance.OnMenu;
                @Menu.performed += instance.OnMenu;
                @Menu.canceled += instance.OnMenu;
                @ContrastMode.started += instance.OnContrastMode;
                @ContrastMode.performed += instance.OnContrastMode;
                @ContrastMode.canceled += instance.OnContrastMode;
                @REBINDTEST.started += instance.OnREBINDTEST;
                @REBINDTEST.performed += instance.OnREBINDTEST;
                @REBINDTEST.canceled += instance.OnREBINDTEST;
                @Logbook.started += instance.OnLogbook;
                @Logbook.performed += instance.OnLogbook;
                @Logbook.canceled += instance.OnLogbook;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // PuzzleDEBUGGER
    private readonly InputActionMap m_PuzzleDEBUGGER;
    private IPuzzleDEBUGGERActions m_PuzzleDEBUGGERActionsCallbackInterface;
    private readonly InputAction m_PuzzleDEBUGGER_calculatesolution;
    private readonly InputAction m_PuzzleDEBUGGER_ShowSolution;
    private readonly InputAction m_PuzzleDEBUGGER_PressAnyButton;
    private readonly InputAction m_PuzzleDEBUGGER_BlindMode;
    private readonly InputAction m_PuzzleDEBUGGER_AutoPilotPuzzle;
    private readonly InputAction m_PuzzleDEBUGGER_ToggleFullAutopilot;
    private readonly InputAction m_PuzzleDEBUGGER_SolvePuzzle;
    public struct PuzzleDEBUGGERActions
    {
        private @InputMaster m_Wrapper;
        public PuzzleDEBUGGERActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @calculatesolution => m_Wrapper.m_PuzzleDEBUGGER_calculatesolution;
        public InputAction @ShowSolution => m_Wrapper.m_PuzzleDEBUGGER_ShowSolution;
        public InputAction @PressAnyButton => m_Wrapper.m_PuzzleDEBUGGER_PressAnyButton;
        public InputAction @BlindMode => m_Wrapper.m_PuzzleDEBUGGER_BlindMode;
        public InputAction @AutoPilotPuzzle => m_Wrapper.m_PuzzleDEBUGGER_AutoPilotPuzzle;
        public InputAction @ToggleFullAutopilot => m_Wrapper.m_PuzzleDEBUGGER_ToggleFullAutopilot;
        public InputAction @SolvePuzzle => m_Wrapper.m_PuzzleDEBUGGER_SolvePuzzle;
        public InputActionMap Get() { return m_Wrapper.m_PuzzleDEBUGGER; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PuzzleDEBUGGERActions set) { return set.Get(); }
        public void SetCallbacks(IPuzzleDEBUGGERActions instance)
        {
            if (m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface != null)
            {
                @calculatesolution.started -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnCalculatesolution;
                @calculatesolution.performed -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnCalculatesolution;
                @calculatesolution.canceled -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnCalculatesolution;
                @ShowSolution.started -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnShowSolution;
                @ShowSolution.performed -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnShowSolution;
                @ShowSolution.canceled -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnShowSolution;
                @PressAnyButton.started -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnPressAnyButton;
                @PressAnyButton.performed -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnPressAnyButton;
                @PressAnyButton.canceled -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnPressAnyButton;
                @BlindMode.started -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnBlindMode;
                @BlindMode.performed -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnBlindMode;
                @BlindMode.canceled -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnBlindMode;
                @AutoPilotPuzzle.started -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnAutoPilotPuzzle;
                @AutoPilotPuzzle.performed -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnAutoPilotPuzzle;
                @AutoPilotPuzzle.canceled -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnAutoPilotPuzzle;
                @ToggleFullAutopilot.started -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnToggleFullAutopilot;
                @ToggleFullAutopilot.performed -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnToggleFullAutopilot;
                @ToggleFullAutopilot.canceled -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnToggleFullAutopilot;
                @SolvePuzzle.started -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnSolvePuzzle;
                @SolvePuzzle.performed -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnSolvePuzzle;
                @SolvePuzzle.canceled -= m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface.OnSolvePuzzle;
            }
            m_Wrapper.m_PuzzleDEBUGGERActionsCallbackInterface = instance;
            if (instance != null)
            {
                @calculatesolution.started += instance.OnCalculatesolution;
                @calculatesolution.performed += instance.OnCalculatesolution;
                @calculatesolution.canceled += instance.OnCalculatesolution;
                @ShowSolution.started += instance.OnShowSolution;
                @ShowSolution.performed += instance.OnShowSolution;
                @ShowSolution.canceled += instance.OnShowSolution;
                @PressAnyButton.started += instance.OnPressAnyButton;
                @PressAnyButton.performed += instance.OnPressAnyButton;
                @PressAnyButton.canceled += instance.OnPressAnyButton;
                @BlindMode.started += instance.OnBlindMode;
                @BlindMode.performed += instance.OnBlindMode;
                @BlindMode.canceled += instance.OnBlindMode;
                @AutoPilotPuzzle.started += instance.OnAutoPilotPuzzle;
                @AutoPilotPuzzle.performed += instance.OnAutoPilotPuzzle;
                @AutoPilotPuzzle.canceled += instance.OnAutoPilotPuzzle;
                @ToggleFullAutopilot.started += instance.OnToggleFullAutopilot;
                @ToggleFullAutopilot.performed += instance.OnToggleFullAutopilot;
                @ToggleFullAutopilot.canceled += instance.OnToggleFullAutopilot;
                @SolvePuzzle.started += instance.OnSolvePuzzle;
                @SolvePuzzle.performed += instance.OnSolvePuzzle;
                @SolvePuzzle.canceled += instance.OnSolvePuzzle;
            }
        }
    }
    public PuzzleDEBUGGERActions @PuzzleDEBUGGER => new PuzzleDEBUGGERActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_BackToMain;
    private readonly InputAction m_UI_RestartScene;
    public struct UIActions
    {
        private @InputMaster m_Wrapper;
        public UIActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @BackToMain => m_Wrapper.m_UI_BackToMain;
        public InputAction @RestartScene => m_Wrapper.m_UI_RestartScene;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @BackToMain.started -= m_Wrapper.m_UIActionsCallbackInterface.OnBackToMain;
                @BackToMain.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnBackToMain;
                @BackToMain.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnBackToMain;
                @RestartScene.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRestartScene;
                @RestartScene.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRestartScene;
                @RestartScene.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRestartScene;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @BackToMain.started += instance.OnBackToMain;
                @BackToMain.performed += instance.OnBackToMain;
                @BackToMain.canceled += instance.OnBackToMain;
                @RestartScene.started += instance.OnRestartScene;
                @RestartScene.performed += instance.OnRestartScene;
                @RestartScene.canceled += instance.OnRestartScene;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // OneSwitch
    private readonly InputActionMap m_OneSwitch;
    private IOneSwitchActions m_OneSwitchActionsCallbackInterface;
    private readonly InputAction m_OneSwitch_OnlyButton;
    private readonly InputAction m_OneSwitch_PuzzleTest;
    public struct OneSwitchActions
    {
        private @InputMaster m_Wrapper;
        public OneSwitchActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @OnlyButton => m_Wrapper.m_OneSwitch_OnlyButton;
        public InputAction @PuzzleTest => m_Wrapper.m_OneSwitch_PuzzleTest;
        public InputActionMap Get() { return m_Wrapper.m_OneSwitch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OneSwitchActions set) { return set.Get(); }
        public void SetCallbacks(IOneSwitchActions instance)
        {
            if (m_Wrapper.m_OneSwitchActionsCallbackInterface != null)
            {
                @OnlyButton.started -= m_Wrapper.m_OneSwitchActionsCallbackInterface.OnOnlyButton;
                @OnlyButton.performed -= m_Wrapper.m_OneSwitchActionsCallbackInterface.OnOnlyButton;
                @OnlyButton.canceled -= m_Wrapper.m_OneSwitchActionsCallbackInterface.OnOnlyButton;
                @PuzzleTest.started -= m_Wrapper.m_OneSwitchActionsCallbackInterface.OnPuzzleTest;
                @PuzzleTest.performed -= m_Wrapper.m_OneSwitchActionsCallbackInterface.OnPuzzleTest;
                @PuzzleTest.canceled -= m_Wrapper.m_OneSwitchActionsCallbackInterface.OnPuzzleTest;
            }
            m_Wrapper.m_OneSwitchActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OnlyButton.started += instance.OnOnlyButton;
                @OnlyButton.performed += instance.OnOnlyButton;
                @OnlyButton.canceled += instance.OnOnlyButton;
                @PuzzleTest.started += instance.OnPuzzleTest;
                @PuzzleTest.performed += instance.OnPuzzleTest;
                @PuzzleTest.canceled += instance.OnPuzzleTest;
            }
        }
    }
    public OneSwitchActions @OneSwitch => new OneSwitchActions(this);
    private int m_StndKBMSchemeIndex = -1;
    public InputControlScheme StndKBMScheme
    {
        get
        {
            if (m_StndKBMSchemeIndex == -1) m_StndKBMSchemeIndex = asset.FindControlSchemeIndex("Stnd KBM");
            return asset.controlSchemes[m_StndKBMSchemeIndex];
        }
    }
    private int m_xboxcontrollerSchemeIndex = -1;
    public InputControlScheme xboxcontrollerScheme
    {
        get
        {
            if (m_xboxcontrollerSchemeIndex == -1) m_xboxcontrollerSchemeIndex = asset.FindControlSchemeIndex("xboxcontroller");
            return asset.controlSchemes[m_xboxcontrollerSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnExitPuzzle(InputAction.CallbackContext context);
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnAnykey(InputAction.CallbackContext context);
        void OnMenu(InputAction.CallbackContext context);
        void OnContrastMode(InputAction.CallbackContext context);
        void OnREBINDTEST(InputAction.CallbackContext context);
        void OnLogbook(InputAction.CallbackContext context);
    }
    public interface IPuzzleDEBUGGERActions
    {
        void OnCalculatesolution(InputAction.CallbackContext context);
        void OnShowSolution(InputAction.CallbackContext context);
        void OnPressAnyButton(InputAction.CallbackContext context);
        void OnBlindMode(InputAction.CallbackContext context);
        void OnAutoPilotPuzzle(InputAction.CallbackContext context);
        void OnToggleFullAutopilot(InputAction.CallbackContext context);
        void OnSolvePuzzle(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnBackToMain(InputAction.CallbackContext context);
        void OnRestartScene(InputAction.CallbackContext context);
    }
    public interface IOneSwitchActions
    {
        void OnOnlyButton(InputAction.CallbackContext context);
        void OnPuzzleTest(InputAction.CallbackContext context);
    }
}
